name             'gliderlabs_registrator'
maintainer       'Petr Belyaev'
maintainer_email 'upcfrost@gmail.com'
license          'All rights reserved'
description      'Installs/Configures gliderlabs_registrator'
long_description 'Installs/Configures gliderlabs_registrator'
version          '0.1.0'
source_url       'https://github.com/upcFrost/gliderlabs_registrator'
issues_url       'https://github.com/upcFrost/gliderlabs_registrator/issues'

depends 'docker'
depends 'golang'
