name             'gliderlabs_registrator'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures gliderlabs_registrator'
long_description 'Installs/Configures gliderlabs_registrator'
version          '0.1.0'
